id: P002948
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25485
  title: ཤེས་བྱ་དྲིས་བརྒྱ་བ། ས་རྒྱུས་ཤེས་བྱ།
  author: ''
  volumes:
    40837576a77145849e3a4b48c7394ff9:
      image_group_id: I1KG25487
      title: ''
      volume_number: 1
      total_pages: 162
