id: IB2FB8BEB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T02:44:13+00:00'
last_modified: '2022-06-07T16:25:03.234401+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25485
  title: ཤེས་བྱ་དྲིས་བརྒྱ་བ། ས་རྒྱུས་ཤེས་བྱ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    C0C0:
      image_group_id: I1KG25487
      title: ''
      total_pages: 162
      order: 1
      base_file: C0C0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
